/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shutdown;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.imageio.ImageIO;



/**
 *
 * @author hp
 */
public class Shut extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form Shut
     */
    int xMouse;
    int yMouse;
    Thread t;
    public Shut() {
        initComponents();
     //   seticon();
        t = new Thread(this,"child");
        t.start();
    }
 /*   public void seticon()
    {
        try 
        {
        Image i = ImageIO.read(getClass().getResource("/shutdown/images/icon8_Windows8_40px_1.png"));
        setIconImage(i);
        }
        catch(IOException e)
        {}
    }*/

    public void run()
    {
        try
        {
        while(true)
        {
        Calendar cal = new GregorianCalendar();
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        
       
        if(second>=0 && second<=9)
        {
            seco.setText("0"+Integer.toString(second));
        }
        else
            seco.setText(Integer.toString(second));
        if(minute>=0 && minute<=9)
        {
            mint.setText("0"+Integer.toString(minute));
        }
        else
             mint.setText(Integer.toString(minute));
        if(hour>=0 && hour<=9)
        {
            hourr.setText("0"+Integer.toString(hour));
        }
        else
            hourr.setText(Integer.toString(hour));
        t.sleep(1000);
        }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        poweroff = new javax.swing.JLabel();
        signout = new javax.swing.JLabel();
        restart = new javax.swing.JLabel();
        hibernet = new javax.swing.JLabel();
        sleep = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        seco = new javax.swing.JTextField();
        mint = new javax.swing.JTextField();
        hourr = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(1100, 15));
        setUndecorated(true);
        setOpacity(0.7F);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        poweroff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shutdown/images/icons8_Shutdown_40px_1.png"))); // NOI18N
        poweroff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        poweroff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                poweroffMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                poweroffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                poweroffMouseExited(evt);
            }
        });
        jPanel1.add(poweroff, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 30));

        signout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shutdown/images/icons8_Sign_Out_40px_1.png"))); // NOI18N
        signout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signoutMouseExited(evt);
            }
        });
        jPanel1.add(signout, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, 30));

        restart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shutdown/images/icons8_Restart_40px_3.png"))); // NOI18N
        restart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        restart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restartMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                restartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                restartMouseExited(evt);
            }
        });
        jPanel1.add(restart, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, 30));

        hibernet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shutdown/images/icons8_Hibernate_40px_1.png"))); // NOI18N
        hibernet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hibernet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hibernetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hibernetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hibernetMouseExited(evt);
            }
        });
        jPanel1.add(hibernet, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, 30));

        sleep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shutdown/images/icons8_Lock_40px.png"))); // NOI18N
        sleep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sleep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sleepMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sleepMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sleepMouseExited(evt);
            }
        });
        jPanel1.add(sleep, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, 50));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shutdown/images/icons8_Cancel_24px.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 276, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 20));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setForeground(new java.awt.Color(102, 255, 0));
        jTextField1.setBorder(null);
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField1MouseEntered(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 50, 20));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(51, 51, 51));
        jTextField2.setForeground(new java.awt.Color(0, 0, 255));
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 50, 20));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(51, 51, 51));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 50, 20));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(51, 51, 51));
        jTextField4.setForeground(new java.awt.Color(204, 0, 204));
        jTextField4.setBorder(null);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 40, 20));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(51, 51, 51));
        jTextField5.setForeground(new java.awt.Color(255, 0, 0));
        jTextField5.setBorder(null);
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField5MouseEntered(evt);
            }
        });
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 20, 60, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 70));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seco.setEditable(false);
        seco.setBackground(new java.awt.Color(51, 51, 51));
        seco.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 48)); // NOI18N
        seco.setForeground(new java.awt.Color(51, 255, 0));
        seco.setBorder(null);
        jPanel3.add(seco, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 70, 60));

        mint.setEditable(false);
        mint.setBackground(new java.awt.Color(51, 51, 51));
        mint.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 48)); // NOI18N
        mint.setForeground(new java.awt.Color(51, 255, 0));
        mint.setBorder(null);
        jPanel3.add(mint, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 70, 60));

        hourr.setEditable(false);
        hourr.setBackground(new java.awt.Color(51, 51, 51));
        hourr.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 48)); // NOI18N
        hourr.setForeground(new java.awt.Color(51, 255, 0));
        hourr.setBorder(null);
        jPanel3.add(hourr, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 60));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(":");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 20, 50));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(":");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 50));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(51, 51, 51));
        jTextField6.setFont(new java.awt.Font("Tempus Sans ITC", 2, 13)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setBorder(null);
        jPanel3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 200, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 300, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked
    static int i;
    private void poweroffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poweroffMouseClicked
        // TODO add your handling code here:
        i=1;
        Sure s = new Sure();
        s.setVisible(true);
        
    }//GEN-LAST:event_poweroffMouseClicked

    private void restartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restartMouseClicked
        // TODO add your handling code here:
        i=2;
        Sure s = new Sure();
        s.setVisible(true);
        
    }//GEN-LAST:event_restartMouseClicked

    private void signoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signoutMouseClicked
        // TODO add your handling code here:
         i=3;
        Sure s = new Sure();
        s.setVisible(true);
       
    }//GEN-LAST:event_signoutMouseClicked

    private void hibernetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hibernetMouseClicked
        // TODO add your handling code here:
         i=4;
        Sure s = new Sure();
        s.setVisible(true);
        
    }//GEN-LAST:event_hibernetMouseClicked

    private void sleepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sleepMouseClicked
        // TODO add your handling code here:
        final String path = System.getenv("windir") + File.separator + "System32" + File.separator + "rundll32.exe";
     /*   try
        {
                Runtime run=Runtime.getRuntime();
                Process proc=run.exec("Rundll32.exe powrprof.dll,SetSuspendState Sleep");
                System.exit(0);

        }
        catch (Exception e1)
        {
        }*/
      try
        {
                Runtime run=Runtime.getRuntime();
                Process proc=run.exec(path + " user32.dll,LockWorkStation");
                System.exit(0);

        }
        catch (Exception e1)
        {
        }
    }//GEN-LAST:event_sleepMouseClicked

    private void poweroffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poweroffMouseEntered
        // TODO add your handling code here:
        jTextField5.setText("Shutdown");
        
    }//GEN-LAST:event_poweroffMouseEntered

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void restartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restartMouseEntered
        // TODO add your handling code here:
        jTextField1.setText("Restart");
        
    }//GEN-LAST:event_restartMouseEntered

    private void jTextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1MouseEntered

    private void jTextField5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5MouseEntered

    private void signoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signoutMouseEntered
        // TODO add your handling code here:
        jTextField2.setText("Signout");
    }//GEN-LAST:event_signoutMouseEntered

    private void hibernetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hibernetMouseEntered
        // TODO add your handling code here:
        jTextField3.setText("Hibernet");
    }//GEN-LAST:event_hibernetMouseEntered

    private void sleepMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sleepMouseEntered
        // TODO add your handling code here:
        jTextField4.setText("Lock");
    }//GEN-LAST:event_sleepMouseEntered

    private void poweroffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poweroffMouseExited
        // TODO add your handling code here:
        jTextField5.setText("");
    }//GEN-LAST:event_poweroffMouseExited

    private void restartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restartMouseExited
        // TODO add your handling code here:
         jTextField1.setText("");
    }//GEN-LAST:event_restartMouseExited

    private void signoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signoutMouseExited
        // TODO add your handling code here:
         jTextField2.setText("");
    }//GEN-LAST:event_signoutMouseExited

    private void hibernetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hibernetMouseExited
        // TODO add your handling code here:
         jTextField3.setText("");
    }//GEN-LAST:event_hibernetMouseExited

    private void sleepMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sleepMouseExited
        // TODO add your handling code here:
         jTextField4.setText("");
    }//GEN-LAST:event_sleepMouseExited

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        jTextField6.setText("Developed by Lokesh Chandra");
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
        jTextField6.setText("");
    }//GEN-LAST:event_jPanel3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Shut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hibernet;
    private javax.swing.JTextField hourr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField mint;
    private javax.swing.JLabel poweroff;
    private javax.swing.JLabel restart;
    private javax.swing.JTextField seco;
    private javax.swing.JLabel signout;
    private javax.swing.JLabel sleep;
    // End of variables declaration//GEN-END:variables
}
